version: 2
jobs:
  build:
    docker:
      - image: ponkore/hugo:0.1

    working_directory: ~/hugo

    steps:
      - checkout
      - run:
          name: setup
          command: |
              git submodule update -i
              git config --global user.name "ponkore"
              git config --global user.email "ponkore@gmail.com"
              sudo cp /usr/share/zoneinfo/Japan /etc/localtime

      - run:
          name: run hugo
          command: |
              hugo

      - run:
          name: publish
          command: |
              git clone https://github.com/no-sinker/no-sinker.github.io.git
              ls
              cp -rp public/* no-sinker.github.io/
              cd no-sinker.github.io
              ls
              git remote set-url origin git@github.com:no-sinker/no-sinker.github.io.git
              git add .
              git commit -m "[ci skip] publish"
              git push origin master
