name: github pages

on:
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      USERNAME: ponkore

    steps:

    - name: Check out site source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup public repo
      run: |
          git clone --depth 1 https://${USERNAME}:${{ secrets.MY_GITHUB_ACCESS_TOKEN }}@github.com/no-sinker/no-sinker.github.io.git public

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'
        extended: true

    - name: Build
      run: |
        hugo --minify

    - name: Deploy
      run: |
        export MSG=`git log --format=%B -n 1 HEAD`
        cd public
        git config --local user.name "Masao KATO"
        git config --local user.email "ponkore@gmail.com"
        git add .
        git commit -m "${MSG}"
        git push origin master
