name: Deploy

on:
  push:
    branches:
    - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      USERNAME: ponkore

    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: install hugo
      run: |
        go get -u github.com/gohugoio/hugo

    - name: setup public repo
      run: |
          git clone --depth 1 https://ponkore:${{ secrets.MY_GITHUB_ACCESS_TOKEN }}@github.com/no-sinker/no-sinker.github.io.git public

    - name: Build
      run: |
        export PATH=$PATH:`go env GOPATH`/bin
        git submodule init
        git submodule update
        hugo

    - name: Push
      run: |
        export MSG=`git log --format=%B -n 1 HEAD`
        cd public
        git config --local user.name "Masao KATO"
        git config --local user.email "ponkore@gmail.com"
        git add .
        git commit -m "${MSG}"
        git push origin master
